# Generated by Django 6.1.1 on 2026-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('estimated_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('behavior', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('stray', 'Errant'), ('rescued', 'Secouru'), ('in_shelter', 'En refuge'), ('reserved', 'Réservé'), ('adopted', 'Adopté')], default='in_shelter', max_length=20)),
                ('size', models.CharField(blank=True, choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], max_length=10)),
                ('is_adoptable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('diagnosis', 'Diagnostic'), ('treatment', 'Traitement'), ('vaccine', 'Vaccin'), ('surgery', 'Opération'), ('note', 'Remarque')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'medical entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True)),
                ('shelter_notes', models.TextField(blank=True)),
                ('next_appointment', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
    ]
