# Generated by Django 6.1.1 on 2026-09-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('reports', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='refuge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelters.refuge'),
        ),
        migrations.AddField(
            model_name='animal',
            name='source_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_animal', to='reports.report'),
        ),
        migrations.AddField(
            model_name='animalphoto',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='medicalentry',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='medicalentry',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='animals.medicalrecord'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='animals.species'),
        ),
    ]
