# Generated by Django 6.1.1 on 2026-09-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('action_radius_km', models.FloatField(default=20.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='refuges/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_species', models.ManyToManyField(blank=True, related_name='refuges', to='animals.species')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RefugeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('benevole', 'Bénévole'), ('veterinaire', 'Vétérinaire')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('revoked', 'Révoqué')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shelters.refuge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuge_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('refuge', 'user')},
            },
        ),
    ]
