# Generated by Django 6.1.1 on 2026-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuge',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refuge',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
