# Generated by Django 6.1.1 on 2026-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_refuge_position_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuge',
            name='governorate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='refuge',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='refuge',
            name='representative_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='refuge',
            name='rne',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='refuge',
            name='structure',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='refuge',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='refuges/documents/'),
        ),
    ]
