# Generated by Django 6.1.1 on 2026-09-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_benevoleprofile_citoyenprofile_veterinaireprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaireprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='veterinaireprofile',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='veterinaireprofile',
            name='governorate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='veterinaireprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='veterinaires/documents/'),
        ),
        migrations.AddField(
            model_name='veterinaireprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
