# Generated by Django 6.1.1 on 2026-09-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one_time', 'Don ponctuel'), ('sponsorship', 'Parrainage')], default='one_time', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, help_text="Renseigné pour un parrainage d'animal", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='animals.animal')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='shelters.refuge')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
