# Generated by Django 6.1.1 on 2026-09-24 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rescue', 'Secours'), ('transport', 'Transport'), ('medical_emergency', 'Urgence médicale')], default='rescue', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('accepted', 'Prise en charge'), ('en_route', 'En route'), ('on_site', 'Intervention'), ('completed', 'Animal secouru'), ('cancelled', 'Annulée')], default='open', max_length=20)),
                ('target_latitude', models.FloatField()),
                ('target_longitude', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_benevole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_as_benevole', to=settings.AUTH_USER_MODEL)),
                ('assigned_veterinaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_as_veterinaire', to=settings.AUTH_USER_MODEL)),
                ('refuge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='shelters.refuge')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('accepted', 'Prise en charge'), ('en_route', 'En route'), ('on_site', 'Intervention'), ('completed', 'Animal secouru'), ('cancelled', 'Annulée')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_status_changes', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='missions.mission')),
            ],
            options={
                'verbose_name_plural': 'mission status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Acceptée'), ('refused', 'Refusée')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='missions.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('mission', 'user')},
            },
        ),
    ]
