# Generated by Django 6.1.1 on 2026-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_emergency', 'Nouvelle urgence'), ('mission_assigned', 'Mission assignée'), ('adoption_update', 'Mise à jour adoption'), ('vaccine_reminder', 'Rappel vaccin'), ('new_message', 'Nouveau message'), ('request_accepted', 'Demande acceptée'), ('conversation_blocked', 'Conversation bloquée'), ('new_report', 'Nouveau signalement'), ('other', 'Autre')], default='other', max_length=30),
        ),
    ]
